# GitHub Pages configuration for BikeStylish.ro API
title: BikeStylish.ro Official API
description: Free REST API for BikeStylish.ro products - 5,437 bicycle products and 101 categories from Romania's first AI-integrated online bicycle parts and accessories store

# Basic Jekyll settings
baseurl: ""
url: "https://endimion2k.github.io"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Only use GitHub Pages supported plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - scripts/
  - __pycache__/
  - "*.py"
  - "*.log"
  - "requirements.txt"
  - "*.txt"
  - "*.csv" 
  - "*.xls"
  - backups/
  - vendor/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - JEKYLL_FIX.md

# Include hidden files that should be processed  
include:
  - .htaccess

# SEO and metadata
author: BikeStylish.ro
twitter:
  username: bikestylish
facebook:
  publisher: https://www.facebook.com/BikeStylish

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: BikeStylish.ro
